### ISSUE TITLE
Plug-In never turns on, client log complaining about shader storage buffer binding value

### ISSUE THREAD

**Issue by Frumpis1** [RS117/RLHD#65] opened 2021-09-14 03:18 UTC
1. Installed plugin
2, clicked the "on" switch
3. Game pauses...
4. Switch is set to "off" again, no HD graphic :c

**Client log below**
[frump's error - client.log](https://github.com/RS117/RLHD/files/7158651/frump.s.error.-.client.log)

Thank you, cheers to your great work 😄

**Comment by JorisBlanken** [comment] 2021-09-14 03:28
Duplicate of #19

**Comment by sosodev** [comment] 2022-02-12 08:07
closing since this is a duplicate

**Closed by sosodev** 2022-02-12 08:07 UTC
